language: python

python: 3.5
sudo: required

env:
  global:
    - TRAVIS_NODE_VERSION="6"
  matrix:
    - TEST_TYPE="unit"
#    - TEST_TYPE="e2e"

services:
    - docker

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
    - pip
    - npm

before_install:
    - docker-compose pull
    - chmod a+x ./scripts/*
    - docker-compose up -d
script:
    - ./scripts/install_run_$TEST_TYPE.sh
after_script:
    - test $TEST_TYPE = "e2e" && killall -9 python
after_success:
    - test $TEST_TYPE = "unit" && coveralls-lcov -v -n coverage/lcov.info > coverage.json && coveralls --merge=coverage.json
