elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
        - "9200:9200"
    environment:
        - discovery.type=single-node

mongo:
    image: mongo:3.4
    ports:
        - "27017:27017"

redis: 
    image: redis:3
    ports:
        - "6379:6379"

